version: "3"
services:
  front-end:
    container_name: deno
    build: .
    restart: always
  proxy:
    container_name: nginx
    image: jonasal/nginx-certbot
    environment:
      - CERTBOT_EMAIL=jiechenmc@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d
  loqi-fs:
    container_name: loqi-fs
    build: ./loqi-fs
    restart: always
