version: "3"
services:
  front-end:
    container_name: deno
    build: .
    restart: always
  proxy:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
  loqi-fs:
    container_name: loqi-fs
    build: ./loqi-fs
    restart: always
