version: "3"
services:
  front-end:
    container_name: deno
    build: .
    restart: always
  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    environment:
      - CERTBOT_EMAIL=jiechenmc@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - front-end
      - loqi-fs
  loqi-fs:
    container_name: loqi-fs
    build: ./loqi-fs
    restart: always

volumes:
  nginx_secrets:
